NP-2660: Title with whitespace now working
BIBSYSDEV/nva-cristin-projects pull request #56
Opened 2021-06-07 08:24 UTC by torarnet

Replaces spaces with + symbol according to W3C spec

2021-06-07 09:54 UTC, axthosarouris approved these changes

2021-06-07 18:36 UTC, brinxmat requested changes

2021-06-07 18:36 UTC, brinxmat commented on src/main/java/no/unit/nva/cristin/projects/UriUtils.java
> +        return text.replaceAll(" +", "+");
maybe "\s+" and extract constants to make it clear what is matched here and what the replacement is

2021-06-08 11:02 UTC, janbj approved these changes

2021-06-08 11:23 UTC, axthosarouris approved these changes

2021-06-09 06:52 UTC, brinxmat approved these changes

2021-06-09 07:24 UTC, merged